[default]
extend-ignore-re = [
    # Match rgb-style encoded strings with underscores, tildes, dashes — 6 hyphen-separated segments
    "[0-9A-Za-z_~]{7,}-[0-9A-Za-z_~]{7,}-[0-9A-Za-z_~]{7,}-[0-9A-Za-z_~]{7,}-[0-9A-Za-z_~]{7,}-[0-9A-Za-z_~]{7,}",
    # Match utxob-like values (if needed)
    "[0-9A-Za-z_~]{7,}(-[0-9A-Za-z_~]{7,}){5}",
]
